[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Nicole Mu√±oz <nicolemprado@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
binary = "^1.0.0"
file = "^0.3.0"
matches = "^0.0.1"
langchain-ollama = "^0.2.0"
langchain-unstructured = "^0.1.5"
langchain-huggingface = "^0.1.2"
text-generation = "^0.7.0"
transformers = "^4.46.2"
google-search-results = "^2.4.2"
numexpr = "^2.10.1"
langchainhub = "^0.1.21"
sentencepiece = "^0.2.0"
jinja2 = "^3.1.4"
bitsandbytes = "^0.44.1"
accelerate = "^1.1.1"
ipywidgets = "^8.1.5"
langgraph = "^0.2.45"
langsmith = "^0.1.142"
langchain = "^0.3.7"
langchain-community = "^0.3.5"
langchain-chroma = "^0.1.4"
pypdf = "^5.1.0"
streamlit = "^1.40.0"
bs4 = "^0.0.2"
notebook = "^7.2.2"
langserve = {extras = ["all"], version = "^0.3.0"}
pypdf = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
